name=CrealityKE
version=0.0.1
author=Mehrab Khavari
maintainer=Mehrab Khavari
sentence=Creality Ender3 V3 KE SDK
paragraph=ESP32 library for communicating with Creality printers over WebSocket.
category=Communication
architectures=esp32